/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegMav;

import org.junit.Test;
import org.junit.*;
import static org.junit.Assert.*;

public class UserRegistrationTest {
	
	public static UserRegMain ob=new UserRegMain();;
	@Test
	public void checkFirstName()
	{
		Assert.assertTrue(ob.validFirstName("Ashok"));
	}
	@Test
	public void checkLastName()
	{
		Assert.assertTrue(ob.validLastName("Kumar"));
	}
	@Test
	public void checkValidEmail()
	{
		Assert.assertTrue(ob.emailValidity("ashok.kumar@gmail.com"));
	}
	@Test
	public void checkValidMobileNumber()
	{
		Assert.assertTrue(ob.validMobileNumber("91 9831081745"));
	}
}
